addons:
  apt:
    packages:
      - gcj-jdk
      - junit4
env:
  global:
    - JAVA_RUNTIME_LIBRARY_PREFIX="/usr/lib/gcc/x86_64-linux-gnu/4.6"
install:
  - |
      export JASMIN_ZIP=$TRAVIS_BUILD_DIR/../jasmin.zip
      wget http://downloads.sourceforge.net/project/jasmin/jasmin/jasmin-2.4/jasmin-2.4.zip -O $JASMIN_ZIP
      unzip -d $TRAVIS_BUILD_DIR/.. $JASMIN_ZIP
      export JASMIN_JAR=$TRAVIS_BUILD_DIR/../jasmin-2.4/jasmin.jar
  - |
      export LIBATOMIC_TAR=$TRAVIS_BUILD_DIR/../libatomic-ops.tar.gz
      wget http://www.ivmaisoft.com/_bin/atomic_ops/libatomic_ops-7.4.2.tar.gz -O $LIBATOMIC_TAR
      tar -C $TRAVIS_BUILD_DIR/.. -xf $LIBATOMIC_TAR
      mv $TRAVIS_BUILD_DIR/../libatomic_ops-7.4.2 $TRAVIS_BUILD_DIR/src/mm/boehm-gc/libatomic_ops
  - |
      export CLASSPATH_TAR=$TRAVIS_BUILD_DIR/../classpath-0.99.tar.gz
      wget ftp://ftp.gnu.org/gnu/classpath/classpath-0.99.tar.gz -O $CLASSPATH_TAR
      tar -C $TRAVIS_BUILD_DIR/.. -xf $CLASSPATH_TAR
      export CLASSPATH_SRC=$TRAVIS_BUILD_DIR/../classpath-0.99
      export CLASSPATH_LOG=$TRAVIS_BUILD_DIR/../classpath.log
      export CLASSPATH_INSTALL=$TRAVIS_BUILD_DIR/../classpath-install
      cd $CLASSPATH_SRC
      ./configure --disable-plugin --disable-Werror --disable-gconf-peer --prefix $CLASSPATH_INSTALL > $CLASSPATH_LOG 2>&1
      tail $CLASSPATH_LOG
      make install > $CLASSPATH_LOG 2>&1
      tail $CLASSPATH_LOG
      cd $TRAVIS_BUILD_DIR
  - ./autogen.sh
script:
  - ./configure --with-java-runtime-library-prefix=$CLASSPATH_INSTALL --with-jasmin-jar=$JASMIN_JAR --with-libatomic-ops=no && make && make test
after_failure:
  - cat config.log
  - tail $CLASSPATH_LOG
